## Artificial Neural Network

#### Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#### Importing the dataset

In [2]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [3]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

#### Encoding categorical data

In [4]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

C:\Users\leandro\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\leandro\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


#### Split the dataset into training and testset

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2 , random_state=0 )

#### Standard Scaling

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

### Part 2 - ANN Build up!

In [7]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [8]:
from keras.layers import Dropout

#### Initialising the ANN

In [9]:
classifier = Sequential()

#### Adding the input layer and the first hidden layer

In [10]:
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
classifier.add(Dropout(p=0.1))

C:\Users\leandro\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.1)`
  


#### Adding the second hidden layer

In [11]:
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
classifier.add(Dropout(p=0.1))

C:\Users\leandro\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.1)`
  


#### Adding the output layer

In [12]:
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))


#### Compiling the ANN

In [13]:
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

#### Fitting the ANN to the Training set

In [14]:
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)


Epoch 1/100
8000/8000 [==============================] - 1s 118us/step - loss: 0.4923 - accuracy: 0.7959
Epoch 2/100
8000/8000 [==============================] - 1s 98us/step - loss: 0.4347 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 108us/step - loss: 0.4327 - accuracy: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 154us/step - loss: 0.4322 - accuracy: 0.7960
Epoch 5/100
8000/8000 [==============================] - 1s 129us/step - loss: 0.4309 - accuracy: 0.7960
Epoch 6/100
8000/8000 [==============================] - 1s 106us/step - loss: 0.4274 - accuracy: 0.7964
Epoch 7/100
8000/8000 [==============================] - 1s 106us/step - loss: 0.4292 - accuracy: 0.8163
Epoch 8/100
8000/8000 [==============================] - 1s 120us/step - loss: 0.4262 - accuracy: 0.8220
Epoch 9/100
8000/8000 [==============================] - 1s 134us/step - loss: 0.4251 - accuracy: 0.8235
Epoch 10/100
8000/8000 [==============================] 

Epoch 78/100
8000/8000 [==============================] - 1s 116us/step - loss: 0.4218 - accuracy: 0.8313
Epoch 79/100
8000/8000 [==============================] - 1s 110us/step - loss: 0.4216 - accuracy: 0.8303
Epoch 80/100
8000/8000 [==============================] - 1s 182us/step - loss: 0.4187 - accuracy: 0.8320
Epoch 81/100
8000/8000 [==============================] - 1s 160us/step - loss: 0.4199 - accuracy: 0.8335
Epoch 82/100
8000/8000 [==============================] - 1s 114us/step - loss: 0.4206 - accuracy: 0.8317
Epoch 83/100
8000/8000 [==============================] - 1s 119us/step - loss: 0.4200 - accuracy: 0.8320
Epoch 84/100
8000/8000 [==============================] - 1s 110us/step - loss: 0.4205 - accuracy: 0.8344
Epoch 85/100
8000/8000 [==============================] - 1s 109us/step - loss: 0.4211 - accuracy: 0.8296
Epoch 86/100
8000/8000 [==============================] - 1s 118us/step - loss: 0.4202 - accuracy: 0.8300
Epoch 87/100
8000/8000 [======================

### Part 3 - Making predictions and evaluating the model

#### Predicting the Test set results

In [15]:
y_pred = classifier.predict(X_test)

In [16]:
prediction=list(y_pred)

In [17]:
prediction

[array([0.2621179], dtype=float32),
 array([0.3324586], dtype=float32),
 array([0.25732088], dtype=float32),
 array([0.08622058], dtype=float32),
 array([0.20221113], dtype=float32),
 array([0.5754768], dtype=float32),
 array([0.06189932], dtype=float32),
 array([0.06925366], dtype=float32),
 array([0.14849576], dtype=float32),
 array([0.5754768], dtype=float32),
 array([0.09117997], dtype=float32),
 array([0.20081285], dtype=float32),
 array([0.3139814], dtype=float32),
 array([0.17096409], dtype=float32),
 array([0.5351948], dtype=float32),
 array([0.38944733], dtype=float32),
 array([0.31457147], dtype=float32),
 array([0.09388152], dtype=float32),
 array([0.06932132], dtype=float32),
 array([0.23189354], dtype=float32),
 array([0.44950622], dtype=float32),
 array([0.0397802], dtype=float32),
 array([0.1644258], dtype=float32),
 array([0.14189336], dtype=float32),
 array([0.0379203], dtype=float32),
 array([0.22279602], dtype=float32),
 array([0.1313925], dtype=float32),
 array([0.1

In [18]:
y_pred = (y_pred > 0.5)

In [19]:
probability_prediction = list(y_pred)

In [20]:
probability_prediction

[array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([ True]),
 array([False]),
 array([False]),
 array([False]),
 array([ True]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([ True]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([ True]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]

#### Making the Confusion Matrix

In [21]:
from sklearn.metrics import confusion_matrix

In [22]:
cm = confusion_matrix(y_test, y_pred)

In [23]:
cm

array([[1556,   39],
       [ 283,  122]], dtype=int64)

In [24]:
model_accuracy= ((cm[0,0]+cm[0,1])/2000)*100

In [25]:
print("Model Accuracy=",model_accuracy)

Model Accuracy= 79.75


#### Predict a single observation

In [26]:
#Geography: France
#Credit Score: 600
#Gender: Male
#Age: 40 years old
#Tenure: 3 years
#Balance: $60000
#Number of Products: 2
#Does this customer have a credit card ? Yes
#Is this customer an Active Member: Yes
#Estimated Salary: $50000


### Process

In [27]:
# 1)Data should be included in the same order
# 2) Data must be included with the same data type(Encoding)

In [28]:
new_prediction = classifier.predict(sc.transform(np.array([[0,0,600,1,40,3,60000,2,1,1,50000]])))

In [29]:
new_prediction= (new_prediction>0.5)

In [30]:
print(" Will the customer leave the bank=",new_prediction[0])

 Will the customer leave the bank= [False]


### Evaluating , Improving and Tuning the ANN

In [31]:
from keras.wrappers.scikit_learn import KerasClassifier

In [40]:
from sklearn.model_selection import GridSearchCV

In [32]:
from sklearn.model_selection import cross_val_score

In [45]:
def build_classifier(optimizer):
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

In [46]:
classifier = KerasClassifier(build_fn = build_classifier)

In [47]:
parameters = {'batch_size': [25, 32],
              'epochs': [100, 500],
              'optimizer': ['adam', 'rmsprop']}

In [48]:
grid_search = GridSearchCV(estimator = classifier,param_grid = parameters,scoring = 'accuracy',cv = 10)

In [49]:
grid_search = grid_search.fit(X_train, y_train)

Epoch 1/100
7200/7200 [==============================] - 0s 61us/step - loss: 0.5569 - accuracy: 0.7967
Epoch 2/100
7200/7200 [==============================] - 0s 40us/step - loss: 0.4353 - accuracy: 0.7971
Epoch 3/100
7200/7200 [==============================] - 0s 39us/step - loss: 0.4291 - accuracy: 0.7971
Epoch 4/100
7200/7200 [==============================] - 0s 43us/step - loss: 0.4258 - accuracy: 0.7971
Epoch 5/100
7200/7200 [==============================] - 0s 57us/step - loss: 0.4229 - accuracy: 0.7971
Epoch 6/100
7200/7200 [==============================] - 0s 43us/step - loss: 0.4202 - accuracy: 0.7979
Epoch 7/100
7200/7200 [==============================] - 0s 41us/step - loss: 0.4180 - accuracy: 0.8188
Epoch 8/100
7200/7200 [==============================] - 0s 39us/step - loss: 0.4162 - accuracy: 0.8229
Epoch 9/100
7200/7200 [==============================] - 0s 37us/step - loss: 0.4152 - accuracy: 0.8260
Epoch 10/100
7200/7200 [==============================] - 0s 35u

7200/7200 [==============================] - 0s 61us/step - loss: 0.3999 - accuracy: 0.8351
Epoch 79/100
7200/7200 [==============================] - 0s 55us/step - loss: 0.3997 - accuracy: 0.8343
Epoch 80/100
7200/7200 [==============================] - 1s 76us/step - loss: 0.4001 - accuracy: 0.8349
Epoch 81/100
7200/7200 [==============================] - 0s 52us/step - loss: 0.3999 - accuracy: 0.8339
Epoch 82/100
7200/7200 [==============================] - 0s 49us/step - loss: 0.3998 - accuracy: 0.8347
Epoch 83/100
7200/7200 [==============================] - 0s 51us/step - loss: 0.3998 - accuracy: 0.8338
Epoch 84/100
7200/7200 [==============================] - 0s 69us/step - loss: 0.3993 - accuracy: 0.8353
Epoch 85/100
7200/7200 [==============================] - 1s 78us/step - loss: 0.3994 - accuracy: 0.8346
Epoch 86/100
7200/7200 [==============================] - 1s 89us/step - loss: 0.3997 - accuracy: 0.8346
Epoch 87/100
7200/7200 [==============================] - 1s 71us/st

7200/7200 [==============================] - 0s 43us/step - loss: 0.4021 - accuracy: 0.8356
Epoch 57/100
7200/7200 [==============================] - 0s 37us/step - loss: 0.4022 - accuracy: 0.8356
Epoch 58/100
7200/7200 [==============================] - 0s 36us/step - loss: 0.4019 - accuracy: 0.8356
Epoch 59/100
7200/7200 [==============================] - 0s 37us/step - loss: 0.4023 - accuracy: 0.8367
Epoch 60/100
7200/7200 [==============================] - 0s 38us/step - loss: 0.4021 - accuracy: 0.8356
Epoch 61/100
7200/7200 [==============================] - 0s 38us/step - loss: 0.4020 - accuracy: 0.8361
Epoch 62/100
7200/7200 [==============================] - 0s 36us/step - loss: 0.4019 - accuracy: 0.8358
Epoch 63/100
7200/7200 [==============================] - 0s 37us/step - loss: 0.4019 - accuracy: 0.8365
Epoch 64/100
7200/7200 [==============================] - 0s 36us/step - loss: 0.4019 - accuracy: 0.8350
Epoch 65/100
7200/7200 [==============================] - 0s 38us/st

7200/7200 [==============================] - 0s 52us/step - loss: 0.3539 - accuracy: 0.8549
Epoch 34/100
7200/7200 [==============================] - 0s 56us/step - loss: 0.3536 - accuracy: 0.8557
Epoch 35/100
7200/7200 [==============================] - 0s 66us/step - loss: 0.3521 - accuracy: 0.8585
Epoch 36/100
7200/7200 [==============================] - 0s 47us/step - loss: 0.3520 - accuracy: 0.8561
Epoch 37/100
7200/7200 [==============================] - 0s 38us/step - loss: 0.3526 - accuracy: 0.8557
Epoch 38/100
7200/7200 [==============================] - 0s 36us/step - loss: 0.3520 - accuracy: 0.8547
Epoch 39/100
7200/7200 [==============================] - 0s 37us/step - loss: 0.3516 - accuracy: 0.8576
Epoch 40/100
7200/7200 [==============================] - 0s 36us/step - loss: 0.3512 - accuracy: 0.8579
Epoch 41/100
7200/7200 [==============================] - 0s 35us/step - loss: 0.3517 - accuracy: 0.8579
Epoch 42/100
7200/7200 [==============================] - 0s 35us/st

7200/7200 [==============================] - 0s 55us/step - loss: 0.4115 - accuracy: 0.8324
Epoch 11/100
7200/7200 [==============================] - 0s 49us/step - loss: 0.4106 - accuracy: 0.8314
Epoch 12/100
7200/7200 [==============================] - 0s 41us/step - loss: 0.4097 - accuracy: 0.8322
Epoch 13/100
7200/7200 [==============================] - 0s 39us/step - loss: 0.4091 - accuracy: 0.8340
Epoch 14/100
7200/7200 [==============================] - 0s 39us/step - loss: 0.4083 - accuracy: 0.8333
Epoch 15/100
7200/7200 [==============================] - 0s 39us/step - loss: 0.4077 - accuracy: 0.8354
Epoch 16/100
7200/7200 [==============================] - 0s 66us/step - loss: 0.4072 - accuracy: 0.8351
Epoch 17/100
7200/7200 [==============================] - 0s 38us/step - loss: 0.4066 - accuracy: 0.8344
Epoch 18/100
7200/7200 [==============================] - 0s 40us/step - loss: 0.4062 - accuracy: 0.8356
Epoch 19/100
7200/7200 [==============================] - 0s 42us/st

7200/7200 [==============================] - 0s 64us/step - loss: 0.3978 - accuracy: 0.8367
Epoch 89/100
7200/7200 [==============================] - 0s 61us/step - loss: 0.3978 - accuracy: 0.8365
Epoch 90/100
7200/7200 [==============================] - 1s 74us/step - loss: 0.3972 - accuracy: 0.8372
Epoch 91/100
7200/7200 [==============================] - 0s 60us/step - loss: 0.3972 - accuracy: 0.8361
Epoch 92/100
7200/7200 [==============================] - 0s 41us/step - loss: 0.3971 - accuracy: 0.8349
Epoch 93/100
7200/7200 [==============================] - 0s 55us/step - loss: 0.3967 - accuracy: 0.8351
Epoch 94/100
7200/7200 [==============================] - 0s 48us/step - loss: 0.3966 - accuracy: 0.8361
Epoch 95/100
7200/7200 [==============================] - 0s 48us/step - loss: 0.3964 - accuracy: 0.8364
Epoch 96/100
7200/7200 [==============================] - 0s 50us/step - loss: 0.3962 - accuracy: 0.8369
Epoch 97/100
7200/7200 [==============================] - 0s 52us/st

7200/7200 [==============================] - 0s 52us/step - loss: 0.4045 - accuracy: 0.8339
Epoch 67/100
7200/7200 [==============================] - 0s 51us/step - loss: 0.4045 - accuracy: 0.8338
Epoch 68/100
7200/7200 [==============================] - 0s 42us/step - loss: 0.4043 - accuracy: 0.8336
Epoch 69/100
7200/7200 [==============================] - 0s 42us/step - loss: 0.4043 - accuracy: 0.8329
Epoch 70/100
7200/7200 [==============================] - 0s 37us/step - loss: 0.4044 - accuracy: 0.8326
Epoch 71/100
7200/7200 [==============================] - 0s 40us/step - loss: 0.4039 - accuracy: 0.8338
Epoch 72/100
7200/7200 [==============================] - 1s 72us/step - loss: 0.4039 - accuracy: 0.8313
Epoch 73/100
7200/7200 [==============================] - 0s 35us/step - loss: 0.4038 - accuracy: 0.8333
Epoch 74/100
7200/7200 [==============================] - 0s 46us/step - loss: 0.4035 - accuracy: 0.8338
Epoch 75/100
7200/7200 [==============================] - 0s 48us/st

Epoch 44/100
7200/7200 [==============================] - 0s 35us/step - loss: 0.3470 - accuracy: 0.8578
Epoch 45/100
7200/7200 [==============================] - 0s 41us/step - loss: 0.3472 - accuracy: 0.8593
Epoch 46/100
7200/7200 [==============================] - 0s 39us/step - loss: 0.3468 - accuracy: 0.8592
Epoch 47/100
7200/7200 [==============================] - 0s 35us/step - loss: 0.3470 - accuracy: 0.8593
Epoch 48/100
7200/7200 [==============================] - 0s 37us/step - loss: 0.3469 - accuracy: 0.8589
Epoch 49/100
7200/7200 [==============================] - 0s 42us/step - loss: 0.3468 - accuracy: 0.8599
Epoch 50/100
7200/7200 [==============================] - 0s 40us/step - loss: 0.3469 - accuracy: 0.8575
Epoch 51/100
7200/7200 [==============================] - 0s 40us/step - loss: 0.3456 - accuracy: 0.8604
Epoch 52/100
7200/7200 [==============================] - 0s 38us/step - loss: 0.3470 - accuracy: 0.8594
Epoch 53/100
7200/7200 [==============================]

7200/7200 [==============================] - 0s 33us/step - loss: 0.4092 - accuracy: 0.8322
Epoch 22/100
7200/7200 [==============================] - 0s 39us/step - loss: 0.4088 - accuracy: 0.8319
Epoch 23/100
7200/7200 [==============================] - 0s 40us/step - loss: 0.4082 - accuracy: 0.8329
Epoch 24/100
7200/7200 [==============================] - 0s 51us/step - loss: 0.4081 - accuracy: 0.8343
Epoch 25/100
7200/7200 [==============================] - 0s 55us/step - loss: 0.4075 - accuracy: 0.8324
Epoch 26/100
7200/7200 [==============================] - 0s 36us/step - loss: 0.4074 - accuracy: 0.8336
Epoch 27/100
7200/7200 [==============================] - 0s 38us/step - loss: 0.4072 - accuracy: 0.8349
Epoch 28/100
7200/7200 [==============================] - 0s 49us/step - loss: 0.4069 - accuracy: 0.8354
Epoch 29/100
7200/7200 [==============================] - 0s 38us/step - loss: 0.4067 - accuracy: 0.8353
Epoch 30/100
7200/7200 [==============================] - 0s 40us/st

7200/7200 [==============================] - 0s 37us/step - loss: 0.4002 - accuracy: 0.8361
Epoch 99/100
7200/7200 [==============================] - 0s 40us/step - loss: 0.4002 - accuracy: 0.8350
Epoch 100/100
7200/7200 [==============================] - 0s 44us/step - loss: 0.4004 - accuracy: 0.8351
Epoch 1/100
7200/7200 [==============================] - 0s 60us/step - loss: 0.5624 - accuracy: 0.7956
Epoch 2/100
7200/7200 [==============================] - 0s 44us/step - loss: 0.4363 - accuracy: 0.7962
Epoch 3/100
7200/7200 [==============================] - 0s 48us/step - loss: 0.4304 - accuracy: 0.7962
Epoch 4/100
7200/7200 [==============================] - 0s 64us/step - loss: 0.4282 - accuracy: 0.7962
Epoch 5/100
7200/7200 [==============================] - 0s 58us/step - loss: 0.4262 - accuracy: 0.7962
Epoch 6/100
7200/7200 [==============================] - 0s 54us/step - loss: 0.4232 - accuracy: 0.7962
Epoch 7/100
7200/7200 [==============================] - 0s 52us/step - l

7200/7200 [==============================] - 0s 38us/step - loss: 0.3979 - accuracy: 0.8360
Epoch 77/100
7200/7200 [==============================] - 0s 35us/step - loss: 0.3983 - accuracy: 0.8350
Epoch 78/100
7200/7200 [==============================] - 0s 35us/step - loss: 0.3979 - accuracy: 0.8357
Epoch 79/100
7200/7200 [==============================] - 0s 34us/step - loss: 0.3979 - accuracy: 0.8351
Epoch 80/100
7200/7200 [==============================] - 0s 35us/step - loss: 0.3977 - accuracy: 0.8358
Epoch 81/100
7200/7200 [==============================] - 0s 34us/step - loss: 0.3983 - accuracy: 0.8363
Epoch 82/100
7200/7200 [==============================] - 0s 34us/step - loss: 0.3979 - accuracy: 0.8364
Epoch 83/100
7200/7200 [==============================] - 0s 35us/step - loss: 0.3976 - accuracy: 0.8356
Epoch 84/100
7200/7200 [==============================] - 0s 34us/step - loss: 0.3978 - accuracy: 0.8365
Epoch 85/100
7200/7200 [==============================] - 0s 34us/st

7200/7200 [==============================] - 0s 50us/step - loss: 0.3986 - accuracy: 0.8365
Epoch 55/100
7200/7200 [==============================] - 0s 47us/step - loss: 0.3990 - accuracy: 0.8369
Epoch 56/100
7200/7200 [==============================] - 0s 48us/step - loss: 0.3980 - accuracy: 0.8364
Epoch 57/100
7200/7200 [==============================] - 0s 47us/step - loss: 0.3986 - accuracy: 0.8357
Epoch 58/100
7200/7200 [==============================] - 0s 37us/step - loss: 0.3983 - accuracy: 0.8374
Epoch 59/100
7200/7200 [==============================] - 0s 48us/step - loss: 0.3978 - accuracy: 0.8381
Epoch 60/100
7200/7200 [==============================] - 0s 35us/step - loss: 0.3982 - accuracy: 0.8372
Epoch 61/100
7200/7200 [==============================] - 0s 45us/step - loss: 0.3984 - accuracy: 0.8360
Epoch 62/100
7200/7200 [==============================] - 0s 51us/step - loss: 0.3974 - accuracy: 0.8378
Epoch 63/100
7200/7200 [==============================] - 0s 35us/st

7200/7200 [==============================] - 1s 85us/step - loss: 0.4086 - accuracy: 0.8346
Epoch 33/100
7200/7200 [==============================] - 1s 189us/step - loss: 0.4081 - accuracy: 0.8358
Epoch 34/100
7200/7200 [==============================] - 1s 101us/step - loss: 0.4078 - accuracy: 0.8344
Epoch 35/100
7200/7200 [==============================] - 0s 60us/step - loss: 0.4079 - accuracy: 0.8325
Epoch 36/100
7200/7200 [==============================] - 0s 62us/step - loss: 0.4077 - accuracy: 0.8343
Epoch 37/100
7200/7200 [==============================] - 1s 80us/step - loss: 0.4076 - accuracy: 0.8349
Epoch 38/100
7200/7200 [==============================] - 0s 50us/step - loss: 0.4073 - accuracy: 0.8335
Epoch 39/100
7200/7200 [==============================] - 0s 55us/step - loss: 0.4070 - accuracy: 0.8338
Epoch 40/100
7200/7200 [==============================] - 0s 41us/step - loss: 0.4066 - accuracy: 0.8335
Epoch 41/100
7200/7200 [==============================] - 0s 42us/

7200/7200 [==============================] - 0s 30us/step - loss: 0.3760 - accuracy: 0.8338
Epoch 11/100
7200/7200 [==============================] - 0s 31us/step - loss: 0.3725 - accuracy: 0.8436
Epoch 12/100
7200/7200 [==============================] - 0s 30us/step - loss: 0.3702 - accuracy: 0.8435
Epoch 13/100
7200/7200 [==============================] - 0s 37us/step - loss: 0.3688 - accuracy: 0.8446
Epoch 14/100
7200/7200 [==============================] - 0s 33us/step - loss: 0.3661 - accuracy: 0.8483
Epoch 15/100
7200/7200 [==============================] - 0s 28us/step - loss: 0.3638 - accuracy: 0.8487
Epoch 16/100
7200/7200 [==============================] - 0s 32us/step - loss: 0.3632 - accuracy: 0.8508
Epoch 17/100
7200/7200 [==============================] - 0s 30us/step - loss: 0.3613 - accuracy: 0.8525
Epoch 18/100
7200/7200 [==============================] - 0s 30us/step - loss: 0.3596 - accuracy: 0.8522
Epoch 19/100
7200/7200 [==============================] - 0s 29us/st

7200/7200 [==============================] - 0s 69us/step - loss: 0.3372 - accuracy: 0.8615
Epoch 89/100
7200/7200 [==============================] - 0s 69us/step - loss: 0.3384 - accuracy: 0.8621
Epoch 90/100
7200/7200 [==============================] - 1s 100us/step - loss: 0.3385 - accuracy: 0.8604
Epoch 91/100
7200/7200 [==============================] - 1s 104us/step - loss: 0.3388 - accuracy: 0.8629
Epoch 92/100
7200/7200 [==============================] - 0s 41us/step - loss: 0.3386 - accuracy: 0.8612
Epoch 93/100
7200/7200 [==============================] - 0s 37us/step - loss: 0.3374 - accuracy: 0.8625
Epoch 94/100
7200/7200 [==============================] - 0s 37us/step - loss: 0.3387 - accuracy: 0.8629
Epoch 95/100
7200/7200 [==============================] - 1s 70us/step - loss: 0.3380 - accuracy: 0.8612
Epoch 96/100
7200/7200 [==============================] - 0s 45us/step - loss: 0.3380 - accuracy: 0.8612
Epoch 97/100
7200/7200 [==============================] - 0s 53us/

7200/7200 [==============================] - 0s 40us/step - loss: 0.4015 - accuracy: 0.8356
Epoch 66/100
7200/7200 [==============================] - 0s 40us/step - loss: 0.4012 - accuracy: 0.8360
Epoch 67/100
7200/7200 [==============================] - 0s 39us/step - loss: 0.4012 - accuracy: 0.8371
Epoch 68/100
7200/7200 [==============================] - 0s 39us/step - loss: 0.4013 - accuracy: 0.8357
Epoch 69/100
7200/7200 [==============================] - 0s 41us/step - loss: 0.4008 - accuracy: 0.8344
Epoch 70/100
7200/7200 [==============================] - 0s 40us/step - loss: 0.4008 - accuracy: 0.8375
Epoch 71/100
7200/7200 [==============================] - 0s 47us/step - loss: 0.4008 - accuracy: 0.8371
Epoch 72/100
7200/7200 [==============================] - 0s 49us/step - loss: 0.4010 - accuracy: 0.8374
Epoch 73/100
7200/7200 [==============================] - 0s 41us/step - loss: 0.4004 - accuracy: 0.8365
Epoch 74/100
7200/7200 [==============================] - 0s 40us/st

7200/7200 [==============================] - 0s 64us/step - loss: 0.4040 - accuracy: 0.8364
Epoch 43/100
7200/7200 [==============================] - 0s 41us/step - loss: 0.4038 - accuracy: 0.8361
Epoch 44/100
7200/7200 [==============================] - 0s 65us/step - loss: 0.4041 - accuracy: 0.8361
Epoch 45/100
7200/7200 [==============================] - 1s 72us/step - loss: 0.4035 - accuracy: 0.8349
Epoch 46/100
7200/7200 [==============================] - 1s 71us/step - loss: 0.4032 - accuracy: 0.8367
Epoch 47/100
7200/7200 [==============================] - 0s 61us/step - loss: 0.4032 - accuracy: 0.8353
Epoch 48/100
7200/7200 [==============================] - 1s 73us/step - loss: 0.4028 - accuracy: 0.8365
Epoch 49/100
7200/7200 [==============================] - 0s 64us/step - loss: 0.4033 - accuracy: 0.8361
Epoch 50/100
7200/7200 [==============================] - 0s 46us/step - loss: 0.4033 - accuracy: 0.8363
Epoch 51/100
7200/7200 [==============================] - 0s 40us/st

7200/7200 [==============================] - 0s 31us/step - loss: 0.3968 - accuracy: 0.8340
Epoch 20/100
7200/7200 [==============================] - 0s 34us/step - loss: 0.3962 - accuracy: 0.8349
Epoch 21/100
7200/7200 [==============================] - 0s 30us/step - loss: 0.3954 - accuracy: 0.8344
Epoch 22/100
7200/7200 [==============================] - 0s 31us/step - loss: 0.3953 - accuracy: 0.8354
Epoch 23/100
7200/7200 [==============================] - 0s 49us/step - loss: 0.3950 - accuracy: 0.8368
Epoch 24/100
7200/7200 [==============================] - 0s 36us/step - loss: 0.3948 - accuracy: 0.8340
Epoch 25/100
7200/7200 [==============================] - 0s 29us/step - loss: 0.3941 - accuracy: 0.8346
Epoch 26/100
7200/7200 [==============================] - 0s 29us/step - loss: 0.3939 - accuracy: 0.8350
Epoch 27/100
7200/7200 [==============================] - 0s 31us/step - loss: 0.3935 - accuracy: 0.8358
Epoch 28/100
7200/7200 [==============================] - 0s 33us/st

7200/7200 [==============================] - 0s 51us/step - loss: 0.3389 - accuracy: 0.8603
Epoch 97/100
7200/7200 [==============================] - 0s 46us/step - loss: 0.3387 - accuracy: 0.8619
Epoch 98/100
7200/7200 [==============================] - 0s 39us/step - loss: 0.3389 - accuracy: 0.8607
Epoch 99/100
7200/7200 [==============================] - 0s 39us/step - loss: 0.3388 - accuracy: 0.8629
Epoch 100/100
7200/7200 [==============================] - 0s 44us/step - loss: 0.3396 - accuracy: 0.8601
Epoch 1/100
7200/7200 [==============================] - 0s 68us/step - loss: 0.5467 - accuracy: 0.7937
Epoch 2/100
7200/7200 [==============================] - 0s 52us/step - loss: 0.4401 - accuracy: 0.7937
Epoch 3/100
7200/7200 [==============================] - 0s 43us/step - loss: 0.4347 - accuracy: 0.7937
Epoch 4/100
7200/7200 [==============================] - 0s 42us/step - loss: 0.4314 - accuracy: 0.7937
Epoch 5/100
7200/7200 [==============================] - 0s 42us/step -

7200/7200 [==============================] - 0s 40us/step - loss: 0.4030 - accuracy: 0.8343
Epoch 75/100
7200/7200 [==============================] - 0s 49us/step - loss: 0.4031 - accuracy: 0.8332
Epoch 76/100
7200/7200 [==============================] - 0s 44us/step - loss: 0.4030 - accuracy: 0.8335
Epoch 77/100
7200/7200 [==============================] - 0s 39us/step - loss: 0.4027 - accuracy: 0.8346
Epoch 78/100
7200/7200 [==============================] - 0s 40us/step - loss: 0.4027 - accuracy: 0.8347
Epoch 79/100
7200/7200 [==============================] - 0s 40us/step - loss: 0.4030 - accuracy: 0.8329
Epoch 80/100
7200/7200 [==============================] - 0s 38us/step - loss: 0.4025 - accuracy: 0.8344
Epoch 81/100
7200/7200 [==============================] - 0s 43us/step - loss: 0.4026 - accuracy: 0.8321
Epoch 82/100
7200/7200 [==============================] - 0s 54us/step - loss: 0.4026 - accuracy: 0.8329
Epoch 83/100
7200/7200 [==============================] - 0s 51us/st

Epoch 52/100
7200/7200 [==============================] - 0s 56us/step - loss: 0.3970 - accuracy: 0.8354
Epoch 53/100
7200/7200 [==============================] - 0s 48us/step - loss: 0.3972 - accuracy: 0.8350
Epoch 54/100
7200/7200 [==============================] - 0s 41us/step - loss: 0.3970 - accuracy: 0.8371
Epoch 55/100
7200/7200 [==============================] - 0s 38us/step - loss: 0.3966 - accuracy: 0.8357
Epoch 56/100
7200/7200 [==============================] - 0s 42us/step - loss: 0.3963 - accuracy: 0.8361
Epoch 57/100
7200/7200 [==============================] - 0s 54us/step - loss: 0.3962 - accuracy: 0.8378
Epoch 58/100
7200/7200 [==============================] - 0s 53us/step - loss: 0.3960 - accuracy: 0.8358
Epoch 59/100
7200/7200 [==============================] - 0s 58us/step - loss: 0.3960 - accuracy: 0.8356
Epoch 60/100
7200/7200 [==============================] - 0s 46us/step - loss: 0.3960 - accuracy: 0.8360
Epoch 61/100
7200/7200 [==============================]

7200/7200 [==============================] - 0s 51us/step - loss: 0.3962 - accuracy: 0.8371
Epoch 30/100
7200/7200 [==============================] - 0s 54us/step - loss: 0.3961 - accuracy: 0.8368
Epoch 31/100
7200/7200 [==============================] - 0s 59us/step - loss: 0.3959 - accuracy: 0.8369
Epoch 32/100
7200/7200 [==============================] - 0s 53us/step - loss: 0.3957 - accuracy: 0.8357
Epoch 33/100
7200/7200 [==============================] - 0s 55us/step - loss: 0.3955 - accuracy: 0.8385
Epoch 34/100
7200/7200 [==============================] - 1s 75us/step - loss: 0.3954 - accuracy: 0.8382
Epoch 35/100
7200/7200 [==============================] - 0s 48us/step - loss: 0.3954 - accuracy: 0.8365
Epoch 36/100
7200/7200 [==============================] - 0s 62us/step - loss: 0.3951 - accuracy: 0.8367
Epoch 37/100
7200/7200 [==============================] - 0s 56us/step - loss: 0.3956 - accuracy: 0.8371
Epoch 38/100
7200/7200 [==============================] - 0s 56us/st

7200/7200 [==============================] - 0s 67us/step - loss: 0.4186 - accuracy: 0.7996
Epoch 7/100
7200/7200 [==============================] - 0s 51us/step - loss: 0.4167 - accuracy: 0.8203
Epoch 8/100
7200/7200 [==============================] - 0s 51us/step - loss: 0.4150 - accuracy: 0.8256
Epoch 9/100
7200/7200 [==============================] - 0s 51us/step - loss: 0.4141 - accuracy: 0.8276
Epoch 10/100
7200/7200 [==============================] - 0s 66us/step - loss: 0.4126 - accuracy: 0.8303
Epoch 11/100
7200/7200 [==============================] - 0s 47us/step - loss: 0.4120 - accuracy: 0.8306
Epoch 12/100
7200/7200 [==============================] - 1s 70us/step - loss: 0.4110 - accuracy: 0.8308
Epoch 13/100
7200/7200 [==============================] - 1s 91us/step - loss: 0.4103 - accuracy: 0.8326
Epoch 14/100
7200/7200 [==============================] - 1s 104us/step - loss: 0.4095 - accuracy: 0.8326
Epoch 15/100
7200/7200 [==============================] - 1s 89us/step

7200/7200 [==============================] - 1s 84us/step - loss: 0.3975 - accuracy: 0.8369
Epoch 85/100
7200/7200 [==============================] - 1s 79us/step - loss: 0.3972 - accuracy: 0.8375
Epoch 86/100
7200/7200 [==============================] - 0s 60us/step - loss: 0.3973 - accuracy: 0.8361
Epoch 87/100
7200/7200 [==============================] - 1s 82us/step - loss: 0.3973 - accuracy: 0.8371
Epoch 88/100
7200/7200 [==============================] - 1s 90us/step - loss: 0.3975 - accuracy: 0.8354
Epoch 89/100
7200/7200 [==============================] - 1s 77us/step - loss: 0.3969 - accuracy: 0.8364
Epoch 90/100
7200/7200 [==============================] - 0s 61us/step - loss: 0.3972 - accuracy: 0.8356
Epoch 91/100
7200/7200 [==============================] - 0s 52us/step - loss: 0.3976 - accuracy: 0.8368
Epoch 92/100
7200/7200 [==============================] - 0s 46us/step - loss: 0.3971 - accuracy: 0.8360
Epoch 93/100
7200/7200 [==============================] - 0s 53us/st

7200/7200 [==============================] - 0s 41us/step - loss: 0.3983 - accuracy: 0.8371
Epoch 62/100
7200/7200 [==============================] - 0s 39us/step - loss: 0.3982 - accuracy: 0.8365
Epoch 63/100
7200/7200 [==============================] - 0s 51us/step - loss: 0.3980 - accuracy: 0.8368
Epoch 64/100
7200/7200 [==============================] - 0s 48us/step - loss: 0.3981 - accuracy: 0.8360
Epoch 65/100
7200/7200 [==============================] - 0s 46us/step - loss: 0.3979 - accuracy: 0.8369
Epoch 66/100
7200/7200 [==============================] - 0s 40us/step - loss: 0.3979 - accuracy: 0.8356 0s - loss: 0.4039 - accuracy: 
Epoch 67/100
7200/7200 [==============================] - 0s 48us/step - loss: 0.3978 - accuracy: 0.8365
Epoch 68/100
7200/7200 [==============================] - 0s 48us/step - loss: 0.3977 - accuracy: 0.8353
Epoch 69/100
7200/7200 [==============================] - 0s 39us/step - loss: 0.3980 - accuracy: 0.8374
Epoch 70/100
7200/7200 [=============

7200/7200 [==============================] - 0s 47us/step - loss: 0.4050 - accuracy: 0.8342
Epoch 39/100
7200/7200 [==============================] - 0s 42us/step - loss: 0.4050 - accuracy: 0.8335
Epoch 40/100
7200/7200 [==============================] - 0s 42us/step - loss: 0.4049 - accuracy: 0.8347
Epoch 41/100
7200/7200 [==============================] - 0s 56us/step - loss: 0.4047 - accuracy: 0.8347
Epoch 42/100
7200/7200 [==============================] - 0s 45us/step - loss: 0.4048 - accuracy: 0.8326
Epoch 43/100
7200/7200 [==============================] - 0s 42us/step - loss: 0.4044 - accuracy: 0.8338
Epoch 44/100
7200/7200 [==============================] - 0s 42us/step - loss: 0.4044 - accuracy: 0.8324
Epoch 45/100
7200/7200 [==============================] - 0s 56us/step - loss: 0.4043 - accuracy: 0.8347
Epoch 46/100
7200/7200 [==============================] - 0s 42us/step - loss: 0.4043 - accuracy: 0.8329
Epoch 47/100
7200/7200 [==============================] - 0s 41us/st

7200/7200 [==============================] - 1s 74us/step - loss: 0.4110 - accuracy: 0.8339
Epoch 16/500
7200/7200 [==============================] - 0s 44us/step - loss: 0.4101 - accuracy: 0.8329
Epoch 17/500
7200/7200 [==============================] - 0s 38us/step - loss: 0.4095 - accuracy: 0.8340
Epoch 18/500
7200/7200 [==============================] - 0s 40us/step - loss: 0.4088 - accuracy: 0.8339
Epoch 19/500
7200/7200 [==============================] - 0s 36us/step - loss: 0.4085 - accuracy: 0.8346
Epoch 20/500
7200/7200 [==============================] - 0s 46us/step - loss: 0.4080 - accuracy: 0.8339
Epoch 21/500
7200/7200 [==============================] - 0s 44us/step - loss: 0.4072 - accuracy: 0.8350
Epoch 22/500
7200/7200 [==============================] - 0s 50us/step - loss: 0.4070 - accuracy: 0.8360
Epoch 23/500
7200/7200 [==============================] - 0s 57us/step - loss: 0.4062 - accuracy: 0.8340
Epoch 24/500
7200/7200 [==============================] - 0s 44us/st

7200/7200 [==============================] - 0s 44us/step - loss: 0.3991 - accuracy: 0.8350
Epoch 93/500
7200/7200 [==============================] - 0s 49us/step - loss: 0.3996 - accuracy: 0.8347
Epoch 94/500
7200/7200 [==============================] - 0s 41us/step - loss: 0.3993 - accuracy: 0.8365
Epoch 95/500
7200/7200 [==============================] - 0s 46us/step - loss: 0.3993 - accuracy: 0.8357
Epoch 96/500
7200/7200 [==============================] - 0s 49us/step - loss: 0.3988 - accuracy: 0.8354
Epoch 97/500
7200/7200 [==============================] - 0s 41us/step - loss: 0.3991 - accuracy: 0.8346
Epoch 98/500
7200/7200 [==============================] - 0s 40us/step - loss: 0.3993 - accuracy: 0.8368
Epoch 99/500
7200/7200 [==============================] - 0s 38us/step - loss: 0.3991 - accuracy: 0.8353
Epoch 100/500
7200/7200 [==============================] - 0s 50us/step - loss: 0.3991 - accuracy: 0.8357
Epoch 101/500
7200/7200 [==============================] - 0s 38us/

7200/7200 [==============================] - 1s 80us/step - loss: 0.3989 - accuracy: 0.8357
Epoch 170/500
7200/7200 [==============================] - 0s 64us/step - loss: 0.3986 - accuracy: 0.8351
Epoch 171/500
7200/7200 [==============================] - 1s 75us/step - loss: 0.3985 - accuracy: 0.8361
Epoch 172/500
7200/7200 [==============================] - 0s 65us/step - loss: 0.3986 - accuracy: 0.8346
Epoch 173/500
7200/7200 [==============================] - 0s 68us/step - loss: 0.3986 - accuracy: 0.8360
Epoch 174/500
7200/7200 [==============================] - 0s 48us/step - loss: 0.3987 - accuracy: 0.8364
Epoch 175/500
7200/7200 [==============================] - 0s 58us/step - loss: 0.3987 - accuracy: 0.8360
Epoch 176/500
7200/7200 [==============================] - 0s 58us/step - loss: 0.3992 - accuracy: 0.8364
Epoch 177/500
7200/7200 [==============================] - 0s 43us/step - loss: 0.3987 - accuracy: 0.8364
Epoch 178/500
7200/7200 [==============================] - 0

7200/7200 [==============================] - 0s 57us/step - loss: 0.3983 - accuracy: 0.8372
Epoch 247/500
7200/7200 [==============================] - 0s 54us/step - loss: 0.3982 - accuracy: 0.8367
Epoch 248/500
7200/7200 [==============================] - 0s 55us/step - loss: 0.3984 - accuracy: 0.8363
Epoch 249/500
7200/7200 [==============================] - 0s 64us/step - loss: 0.3982 - accuracy: 0.8368
Epoch 250/500
7200/7200 [==============================] - 1s 88us/step - loss: 0.3983 - accuracy: 0.8351
Epoch 251/500
7200/7200 [==============================] - 0s 67us/step - loss: 0.3983 - accuracy: 0.8347
Epoch 252/500
7200/7200 [==============================] - 0s 47us/step - loss: 0.3984 - accuracy: 0.8353
Epoch 253/500
7200/7200 [==============================] - 0s 54us/step - loss: 0.3984 - accuracy: 0.8361
Epoch 254/500
7200/7200 [==============================] - 0s 55us/step - loss: 0.3985 - accuracy: 0.8353
Epoch 255/500
7200/7200 [==============================] - 0

7200/7200 [==============================] - 0s 33us/step - loss: 0.3980 - accuracy: 0.8358
Epoch 324/500
7200/7200 [==============================] - 0s 35us/step - loss: 0.3984 - accuracy: 0.8347
Epoch 325/500
7200/7200 [==============================] - 0s 36us/step - loss: 0.3983 - accuracy: 0.8360
Epoch 326/500
7200/7200 [==============================] - 0s 36us/step - loss: 0.3981 - accuracy: 0.8364
Epoch 327/500
7200/7200 [==============================] - 0s 30us/step - loss: 0.3983 - accuracy: 0.8364
Epoch 328/500
7200/7200 [==============================] - 0s 42us/step - loss: 0.3981 - accuracy: 0.8353
Epoch 329/500
7200/7200 [==============================] - 0s 48us/step - loss: 0.3983 - accuracy: 0.8369
Epoch 330/500
7200/7200 [==============================] - 0s 47us/step - loss: 0.3984 - accuracy: 0.8365
Epoch 331/500
7200/7200 [==============================] - 0s 49us/step - loss: 0.3982 - accuracy: 0.8357
Epoch 332/500
7200/7200 [==============================] - 0

7200/7200 [==============================] - 0s 40us/step - loss: 0.3980 - accuracy: 0.8358
Epoch 401/500
7200/7200 [==============================] - 0s 43us/step - loss: 0.3985 - accuracy: 0.8371
Epoch 402/500
7200/7200 [==============================] - 0s 35us/step - loss: 0.3980 - accuracy: 0.8351
Epoch 403/500
7200/7200 [==============================] - 0s 56us/step - loss: 0.3981 - accuracy: 0.8368
Epoch 404/500
7200/7200 [==============================] - 0s 41us/step - loss: 0.3981 - accuracy: 0.8349
Epoch 405/500
7200/7200 [==============================] - 0s 48us/step - loss: 0.3982 - accuracy: 0.8343
Epoch 406/500
7200/7200 [==============================] - 0s 39us/step - loss: 0.3985 - accuracy: 0.8364
Epoch 407/500
7200/7200 [==============================] - 0s 37us/step - loss: 0.3980 - accuracy: 0.8369
Epoch 408/500
7200/7200 [==============================] - 0s 37us/step - loss: 0.3982 - accuracy: 0.8347
Epoch 409/500
7200/7200 [==============================] - 0

7200/7200 [==============================] - 0s 38us/step - loss: 0.3982 - accuracy: 0.8360
Epoch 478/500
7200/7200 [==============================] - 0s 35us/step - loss: 0.3982 - accuracy: 0.8361
Epoch 479/500
7200/7200 [==============================] - 0s 34us/step - loss: 0.3984 - accuracy: 0.8364
Epoch 480/500
7200/7200 [==============================] - 0s 34us/step - loss: 0.3983 - accuracy: 0.8360
Epoch 481/500
7200/7200 [==============================] - 0s 35us/step - loss: 0.3983 - accuracy: 0.8363
Epoch 482/500
7200/7200 [==============================] - 0s 35us/step - loss: 0.3982 - accuracy: 0.8354
Epoch 483/500
7200/7200 [==============================] - 0s 35us/step - loss: 0.3976 - accuracy: 0.8357
Epoch 484/500
7200/7200 [==============================] - 0s 35us/step - loss: 0.3983 - accuracy: 0.8367
Epoch 485/500
7200/7200 [==============================] - 0s 46us/step - loss: 0.3984 - accuracy: 0.8360
Epoch 486/500
7200/7200 [==============================] - 0

7200/7200 [==============================] - 0s 43us/step - loss: 0.4013 - accuracy: 0.8369
Epoch 55/500
7200/7200 [==============================] - 0s 40us/step - loss: 0.4011 - accuracy: 0.8361
Epoch 56/500
7200/7200 [==============================] - 0s 53us/step - loss: 0.4010 - accuracy: 0.8349
Epoch 57/500
7200/7200 [==============================] - 0s 37us/step - loss: 0.4015 - accuracy: 0.8363
Epoch 58/500
7200/7200 [==============================] - 0s 44us/step - loss: 0.4013 - accuracy: 0.8353
Epoch 59/500
7200/7200 [==============================] - 0s 47us/step - loss: 0.4012 - accuracy: 0.8357
Epoch 60/500
7200/7200 [==============================] - 0s 38us/step - loss: 0.4012 - accuracy: 0.8349
Epoch 61/500
7200/7200 [==============================] - 0s 41us/step - loss: 0.4013 - accuracy: 0.8349
Epoch 62/500
7200/7200 [==============================] - 0s 49us/step - loss: 0.4009 - accuracy: 0.8351
Epoch 63/500
7200/7200 [==============================] - 0s 38us/st

KeyboardInterrupt: 

In [50]:
best_parameters = grid_search.best_params_

AttributeError: 'GridSearchCV' object has no attribute 'best_params_'

In [51]:
best_accuracy = grid_search.best_score_

AttributeError: 'GridSearchCV' object has no attribute 'best_score_'