## Artificial Neural Network

#### Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#### Importing the dataset

In [2]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [3]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

#### Encoding categorical data

In [4]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

C:\Users\leandro\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\leandro\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


#### Split the dataset into training and testset

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2 , random_state=0 )

#### Standard Scaling

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

### Part 2 - ANN Build up!

In [7]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [8]:
from keras.layers import Dropout

#### Initialising the ANN

In [9]:
classifier = Sequential()

#### Adding the input layer and the first hidden layer

In [10]:
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
classifier.add(Dropout(p=0.1))

C:\Users\leandro\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.1)`
  


#### Adding the second hidden layer

In [11]:
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
classifier.add(Dropout(p=0.1))

C:\Users\leandro\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.1)`
  


#### Adding the output layer

In [12]:
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))


#### Compiling the ANN

In [13]:
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

#### Fitting the ANN to the Training set

In [14]:
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)


Epoch 1/100
8000/8000 [==============================] - 1s 165us/step - loss: 0.5084 - accuracy: 0.7951
Epoch 2/100
8000/8000 [==============================] - 1s 107us/step - loss: 0.4286 - accuracy: 0.8064
Epoch 3/100
8000/8000 [==============================] - 1s 100us/step - loss: 0.4190 - accuracy: 0.8194
Epoch 4/100
8000/8000 [==============================] - 1s 113us/step - loss: 0.4173 - accuracy: 0.8223
Epoch 5/100
8000/8000 [==============================] - 1s 119us/step - loss: 0.4082 - accuracy: 0.8217
Epoch 6/100
8000/8000 [==============================] - 1s 152us/step - loss: 0.4052 - accuracy: 0.8219
Epoch 7/100
8000/8000 [==============================] - 1s 129us/step - loss: 0.4069 - accuracy: 0.8239
Epoch 8/100
8000/8000 [==============================] - 1s 112us/step - loss: 0.4067 - accuracy: 0.8229
Epoch 9/100
8000/8000 [==============================] - 1s 104us/step - loss: 0.4032 - accuracy: 0.8217
Epoch 10/100
8000/8000 [==============================]

8000/8000 [==============================] - 1s 84us/step - loss: 0.3875 - accuracy: 0.8386
Epoch 79/100
8000/8000 [==============================] - 1s 96us/step - loss: 0.3916 - accuracy: 0.8366
Epoch 80/100
8000/8000 [==============================] - 1s 110us/step - loss: 0.3896 - accuracy: 0.8364
Epoch 81/100
8000/8000 [==============================] - 1s 91us/step - loss: 0.3889 - accuracy: 0.8375
Epoch 82/100
8000/8000 [==============================] - 1s 87us/step - loss: 0.3823 - accuracy: 0.8371
Epoch 83/100
8000/8000 [==============================] - 1s 87us/step - loss: 0.3911 - accuracy: 0.8345
Epoch 84/100
8000/8000 [==============================] - 1s 87us/step - loss: 0.3869 - accuracy: 0.8376
Epoch 85/100
8000/8000 [==============================] - 1s 102us/step - loss: 0.3889 - accuracy: 0.8366
Epoch 86/100
8000/8000 [==============================] - 1s 96us/step - loss: 0.3887 - accuracy: 0.8372
Epoch 87/100
8000/8000 [==============================] - 1s 106us

### Part 3 - Making predictions and evaluating the model

#### Predicting the Test set results

In [15]:
y_pred = classifier.predict(X_test)

In [16]:
prediction=list(y_pred)

In [17]:
prediction

[array([0.2615227], dtype=float32),
 array([0.2496891], dtype=float32),
 array([0.11187033], dtype=float32),
 array([0.06336541], dtype=float32),
 array([0.15015437], dtype=float32),
 array([0.66830105], dtype=float32),
 array([0.06381523], dtype=float32),
 array([0.13463014], dtype=float32),
 array([0.4186971], dtype=float32),
 array([0.66830105], dtype=float32),
 array([0.0541795], dtype=float32),
 array([0.35848844], dtype=float32),
 array([0.28746396], dtype=float32),
 array([0.22701588], dtype=float32),
 array([0.55237585], dtype=float32),
 array([0.26178855], dtype=float32),
 array([0.1924445], dtype=float32),
 array([0.1596198], dtype=float32),
 array([0.06464253], dtype=float32),
 array([0.1423375], dtype=float32),
 array([0.3530365], dtype=float32),
 array([0.02397625], dtype=float32),
 array([0.09964099], dtype=float32),
 array([0.10424743], dtype=float32),
 array([0.02055535], dtype=float32),
 array([0.2218507], dtype=float32),
 array([0.1574685], dtype=float32),
 array([0.0

In [18]:
y_pred = (y_pred > 0.5)

In [19]:
probability_prediction = list(y_pred)

In [20]:
probability_prediction

[array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([ True]),
 array([False]),
 array([False]),
 array([False]),
 array([ True]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([ True]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([ True]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]

#### Making the Confusion Matrix

In [21]:
from sklearn.metrics import confusion_matrix

In [22]:
cm = confusion_matrix(y_test, y_pred)

In [23]:
cm

array([[1548,   47],
       [ 235,  170]], dtype=int64)

In [24]:
model_accuracy= ((cm[0,0]+cm[0,1])/2000)*100

In [25]:
print("Model Accuracy=",model_accuracy)

Model Accuracy= 79.75


#### Predict a single observation

In [26]:
#Geography: France
#Credit Score: 600
#Gender: Male
#Age: 40 years old
#Tenure: 3 years
#Balance: $60000
#Number of Products: 2
#Does this customer have a credit card ? Yes
#Is this customer an Active Member: Yes
#Estimated Salary: $50000


### Process

In [27]:
# 1)Data should be included in the same order
# 2) Data must be included with the same data type(Encoding)

In [28]:
new_prediction = classifier.predict(sc.transform(np.array([[0,0,600,1,40,3,60000,2,1,1,50000]])))

In [29]:
new_prediction= (new_prediction>0.5)

In [30]:
print(" Will the customer leave the bank=",new_prediction[0])

 Will the customer leave the bank= [False]


### Evaluating , Improving and Tuning the ANN

In [31]:
from keras.wrappers.scikit_learn import KerasClassifier

In [32]:
from sklearn.model_selection import cross_val_score

In [33]:
def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

In [34]:
classifier = KerasClassifier(build_fn = build_classifier,batch_size=10,nb_epoch=100)

In [35]:
accuracies = cross_val_score(estimator=classifier,X=X_train,y=y_train,cv=10,n_jobs=-1)

In [36]:
accuracies

array([0.78625   , 0.79000002, 0.80000001, 0.78250003, 0.81625003,
       0.81      , 0.78750002, 0.79374999, 0.79874998, 0.79500002])

In [37]:
mean=accuracies.mean()
mean

0.7960000097751617

In [38]:
variance=accuracies.std()
variance

0.010105690527913859

## Improving the ANN